<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bhushan</groupId>
        <artifactId>sde-engineering-playbook</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>spring</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.</groupId>
            <artifactId>spring-context</artifactId>
            <version>7.0.3</version>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.46</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>
</project>