<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bhushan</groupId>
        <artifactId>sde-engineering-playbook</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>system-design</artifactId>

    <dependencies>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
</project>